<a href="https://colab.research.google.com/github/donkeyson/DataAnalytics/blob/main/Numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
#넘파이 배열 생성하기
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [4]:
#2차원 넘파이 배열
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
b[0][2]

3

In [6]:
#배열의 형상 (n, m) n개의 행과 m개의 열
b.shape

(3, 3)

In [8]:
#차원 개수 (number of dimensions?)
b.ndim

2

In [9]:
#요소의 자료형
#왜 64가 나올까?
b.dtype

dtype('int64')

In [10]:
#요소 한개의 크기. 바이트기준.
b.itemsize

8

In [13]:
#전체 요소의 개수
b.size

9

In [14]:
#(n, m) 0으로 구성된 3행 4열 만들기
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
#(n, m, dtype=np.int32) dtype이 int32인 1로 구성된 3행 4열짜리 만들기
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
#(n) n개의 열과 n개의 행. 대각선 1로 구성
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
#arange() 넘파이의 range함수
np.arange(5)

array([0, 1, 2, 3, 4])

In [20]:
np.arange(1, 6)

array([1, 2, 3, 4, 5])

In [21]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [22]:
#넘파이 정렬
arr = np.array([2, 1, 5, 3, 7, 4, 6, 7])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 7])

In [23]:
#내림차순
np.sort(arr)[::-1]

array([7, 7, 6, 5, 4, 3, 2, 1])

In [25]:
#배열 합치기 열기준으로
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

np.concatenate((x, y), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [26]:
#배열 합치기 행 기준으로 vertical
np.vstack((x,y))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [27]:
#배열 합치기 열 기준으로(same) horizontal
np.hstack((x, y))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [30]:
#reshape() 함수 2행 3열로
old_array = np.array([1, 2, 3, 4, 5, 6])
new_array = old_array.reshape((2, 3))
new_array

array([[1, 2, 3],
       [4, 5, 6]])